Hustlers/Controllers/JobAdvertController.cs
using Hustlers.Domain.Interfaces.Helpers;
using Hustlers.Domain.Interfaces.Services;
using Hustlers.Domain.Models.JobAdvertViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Hustlers.Controllers
{
    public class JobAdvertController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IJobAdvertService _jobAdvertService;
        private readonly IExperienceLevelService _experienceLevelService;
        private readonly IProvinceService _provinceService;
        private readonly IJobTypeService _jobTypeService;
        private readonly IRecruiterService _recruiterService;
        private readonly IJobCategoryService _jobCategoryService;
        private readonly ICityService _cityService;
        private readonly ILogger<JobAdvertController> _logger;
        private readonly IStringManipulator _stringManipulator;

        public JobAdvertController(ICompanyService companyService, IJobAdvertService jobAdvertService, IExperienceLevelService experienceLevelService,
            IProvinceService provinceService, IRecruiterService recruiterService, IJobCategoryService jobCategoryService,IJobTypeService jobTypeService,
            IStringManipulator stringManipulator, ICityService cityService)
        {
            _companyService = companyService;
            _provinceService = provinceService;
            _recruiterService = recruiterService;
            _cityService = cityService;
            _experienceLevelService = experienceLevelService;
            _jobAdvertService = jobAdvertService;
            _jobCategoryService = jobCategoryService;
            _jobTypeService = jobTypeService;
            _stringManipulator = stringManipulator;
        }
        // GET: HomeController
        public ActionResult Index()
        {
            return View(PrepareJobAdvertModel());
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateJobAdvertViewModel createJobAdvertViewModel)
        {

            if(ModelState.IsValid)
            {
                _jobAdvertService.Create(createJobAdvertViewModel);

                return RedirectToAction("Index","Admin");
            }
            else
            {
                return View("Create",PrepareJobAdvertModel());
            }
        }

        private CreateJobAdvertViewModel PrepareJobAdvertModel()
        {
            CreateJobAdvertViewModel createJobAdvertViewModel = new CreateJobAdvertViewModel
            {
                JobCategories = _jobCategoryService.GetAll(),
                JobTypes = _jobTypeService.GetAll(),
                ExperienceLevels = _experienceLevelService.GetAll(),
                Companies = _companyService.GetAll(),
                Recruiters = _recruiterService.Get(),
                Cities = _cityService.GetAll()
            };

            return createJobAdvertViewModel;
        }
        // GET: HomeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomeController/Create
        public ActionResult JobAdvertList()
        {
            return View();
        }     
        
        // GET: HomeController/Create
        public ActionResult RecruiterViewAppliedJobs()
        {
            return View("AdminRecruiterViewAppliedJobs");
        }        
        
        public ActionResult RecruiterAppliedJobsDetails(int id)
        {
            return View("AdminRecruiterAppliedJobDetails");
        }
        

        public ActionResult JobSeekerJobDetails(int id)
        {
            return View("JobSeekerJobAdvertDetails");
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Hustlers/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Hustlers.Domain.Entities;
using Hustlers.Domain.Interfaces.Helpers;
using Hustlers.Domain.Interfaces.Services;
using Hustlers.Domain.Models.SecurityViewModel;
using Hustlers.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Hustlers.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRecruiterService _recruiterService;
        private readonly IJobSeekerService _JobSeekerService;
        private ILogger<UserController> _logger;
        public UserController(IUserService userService, IRecruiterService recruiterService
            ,IJobSeekerService jobSeekerService, ILogger<UserController> logger)
        {
            _userService = userService;
            //_session = session;
            _recruiterService = recruiterService;
            _JobSeekerService = jobSeekerService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.AuthError = "empty";
            return View();
        }

       [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult Auth(User userModel,LoginViewModel loginModel)
        {
            //Return a relevant admin page based on the type of user logging in
            //Do not forget to encrypt a password
            var controller = "";
            HttpContext.Session.Clear();

            var authUser = _userService.AuthUser(userModel);
            //HttpContext.Session.Clear();
            if(authUser != null)
            {
                //Set a session
                //_sessionManager.Set
                if(authUser.RoleName.Equals("Admin"))
                {
                    HttpContext.Session.Set<string>("AdminId",authUser.Id);
                    HttpContext.Session.Set<string>("Role", authUser.RoleName);
                    HttpContext.Session.Set<string>("Username", authUser.Username);
                    controller = "Admin";
                }

                if(authUser.RoleName.Equals("Recruiter"))
                {
                    //var recruiter =_recruiterService.Get(authUser.UserId);
                    HttpContext.Session.Set<string>("RecruiterId", authUser.UserId);
                    HttpContext.Session.Set<string>("Role", authUser.RoleName);
                    HttpContext.Session.Set<string>("Username", authUser.Username);
                    controller = "Recruiter";
                }

                if (authUser.RoleName.Equals("JobSeeker"))
                {
                    //var jobSeeker = _JobSeekerService.Get(authUser.UserId);
                    HttpContext.Session.Set<string>("JobSeekerId", authUser.UserId);
                    HttpContext.Session.Set<string>("Role", authUser.RoleName);
                    HttpContext.Session.Set<string>("Username", authUser.Username);
                    controller = "JobSeeker";
                }
            }
            _logger.LogInformation(HttpContext.Session.Get<string>("Role"));
            return RedirectToAction("Index",controller);

        }

        [HttpPost]
        public ActionResult SignUp(User userModel)
        {
            

            if(ModelState.IsValid)
            {
                userModel.RoleName = "JobSeeker";
                userModel.UserId = Guid.NewGuid().ToString();
                bool isJobSeekerRegistered = _userService.IsUserRegistered(userModel);

                if (isJobSeekerRegistered)
                {
                    return RedirectToAction(nameof(JobSeekerRegistered));
                }
            }
            return View(nameof(Index));
        }

        public ActionResult SignOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(Index));
        }
        //Clear all the sessions
        public ActionResult JobSeekerRegistered()
        {
            ViewBag.Registered = "User successfully registered";
            return View();
        }

    }
}

Hustlers/Views/Shared/_AdminRecruiterInsertSuccess.cshtml
@{
    ViewData["Title"] = "_AdminRecruiterInsertSuccess";
    Layout = "~/Views/Shared/_AdminRecruiterLayout.cshtml";
}

<h1>_AdminRecruiterInsertSuccess</h1>

Hustlers/Views/Shared/_AdminRecruiterLayout.cshtml
@{
    Layout = "_MasterLayout";
    var UserRole = HttpContextAccessor.HttpContext.Session.GetString("Role");
    var sessionValues = HttpContextAccessor.HttpContext.Session;
}

<!-- Page header -->
<div class="page-header page-header-dark">

    <!-- Main navbar -->
    <div class="navbar navbar-expand-md navbar-dark border-transparent">

        <div class="d-md-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
                <i class="icon-tree5"></i>
            </button>
            <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
                <i class="icon-paragraph-justify3"></i>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-mobile">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                        <i class="icon-paragraph-justify3"></i>
                    </a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">

                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link">
                        <i class="icon-bell2"></i>
                        <span class="d-md-none ml-2">Notifications</span>
                        <span class="badge badge-mark border-white ml-auto ml-md-0"></span>
                    </a>
                </li>

                <li class="nav-item dropdown dropdown-user">
                    <a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
                        <img src="../../../../global_assets/images/image.png" class="rounded-circle mr-2" height="34" alt="">
                        <span>@sessionValues.GetString("Username");</span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="#" class="dropdown-item"><i class="icon-user-plus"></i> My profile</a>
                        <a href="#" class="dropdown-item"><i class="icon-cog5"></i> Change Password</a>
                        <div class="dropdown-divider"></div>
                        <a asp-action="SignOut" asp-controller="User" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <!-- /main navbar -->
    <!-- Secondary navbar -->
    <div class="navbar navbar-expand-md navbar-dark border-top-0">
        <div class="text-center d-md-none w-100">
            <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-navigation">
                <i class="icon-unfold mr-2"></i>
                Navigation
            </button>
        </div>

        <div class="navbar-collapse collapse" id="navbar-navigation">
            <ul class="navbar-nav navbar-nav-highlight">
                <li class="nav-item">
                    <a href="../full/index.html" class="navbar-nav-link">
                        <i class="icon-home4 mr-2"></i>
                        Dashboard
                    </a>
                </li>

            </ul>

        </div>
    </div>
    <!-- /secondary navbar -->

</div>
<!-- /page header -->
<!-- Page content -->
<div class="page-content">

    <!-- Main sidebar -->
    <div class="sidebar sidebar-light sidebar-main sidebar-expand-md align-self-start">

        <!-- Sidebar mobile toggler -->
        <div class="sidebar-mobile-toggler text-center">
            <a href="#" class="sidebar-mobile-main-toggle">
                <i class="icon-arrow-left8"></i>
            </a>
            <span class="font-weight-semibold">Main sidebar</span>
            <a href="#" class="sidebar-mobile-expand">
                <i class="icon-screen-full"></i>
                <i class="icon-screen-normal"></i>
            </a>
        </div>
        <!-- /sidebar mobile toggler -->
        <!-- Sidebar content -->
        <div class="sidebar-content">
            <div class="card card-sidebar-mobile">

                <!-- Header -->
                <div class="card-header header-elements-inline">
                    <h6 class="card-title">Navigation</h6>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="collapse"></a>
                        </div>
                    </div>
                </div>
                <!-- /header -->
                <!-- Main navigation -->
                @if (UserRole.Contains("Admin"))
                {
                    <partial name="_AdminSideNavMenu" />
                }
                else
                {
                    <partial name="_RecruiterSideNavMenu" />
                }
                <!-- /main navigation -->

            </div>
        </div>
        <!-- /sidebar content -->

    </div>
    <!-- /main sidebar -->
    <!-- Main content -->
    <div class="content-wrapper">

        <!-- Content area -->
        <div class="content">

            @RenderBody()

        </div>
        <!-- /content area -->

    </div>
    <!-- /main content -->

</div>
<!-- /page content -->

Hustlers/Views/Shared/_AdminSideNavMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!-- Main navigation -->
<div class="card-body p-0">
    <ul class="nav nav-sidebar" data-nav-type="accordion">

        <!-- Main -->
        <li class="nav-item-header mt-0"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
        <li class="nav-item">
            <a  asp-action="Index" asp-controller="Admin" class="nav-link">
                <i class="icon-home4"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <li class="nav-item nav-item-submenu nav-item-expanded nav-item-open">
            <a href="#" class="nav-link"><i class="icon-stack"></i> <span>Recruiter</span></a>

            <ul class="nav nav-group-sub" data-submenu-title="Recruiter">
                <li class="nav-item"><a asp-action="Create" asp-controller="Recruiter" class="nav-link">Create</a></li>
                <li class="nav-item"><a asp-action="AdminViewRecruiter" asp-controller="Recruiter" class="nav-link">View</a></li>
            </ul>
        </li>

        <li class="nav-item nav-item-submenu nav-item-expanded nav-item-open">
            <a href="#" class="nav-link"><i class="icon-unfold"></i> <span>Job Advert</span></a>

            <ul class="nav nav-group-sub" data-submenu-title="Job Advert">
                <li class="nav-item"><a asp-action="Index" asp-controller="JobAdvert" class="nav-link">Create</a></li>
                <li class="nav-item"><a asp-action="JobAdvertList" asp-controller="JobAdvert" class="nav-link">View</a></li>
            </ul>
        </li>

        <!-- <li class="nav-item nav-item-submenu nav-item-expanded nav-item-open">
         <a href="#" class="nav-link"><i class="icon-people"></i> <span>Job Seeker</span></a>

         <ul class="nav nav-group-sub" data-submenu-title="Job Seeker">
             <li class="nav-item"><a asp-action="AdminCreate" asp-controller="Recruiter" class="nav-link">Create</a></li>
             <li class="nav-item"><a asp-action="AdminViewRecruiter" asp-controller="Recruiter" class="nav-link">View</a></li>
         </ul>
     </li> -->

        <li class="nav-item nav-item-submenu nav-item-expanded nav-item-open">
            <a href="#" class="nav-link"><i class="icon-home"></i> <span>Company</span></a>

            <ul class="nav nav-group-sub" data-submenu-title="Company">
                <li class="nav-item"><a asp-action="Create" asp-controller="Company" class="nav-link">Create</a></li>
                <li class="nav-item"><a asp-action="Index" asp-controller="Company" class="nav-link">View</a></li>
            </ul>
        </li>
        <!-- /main -->

    </ul>
</div>
<!-- /main navigation -->

Hustlers/Views/Shared/_JobAdvertCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row mt-2">

    <div class="col-md-6">
        <!--Iterate To display search results-->
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">IT Support</h5>

            </div>

            <div class="card-body">
                <div class="card-subtitle mb-2 text-muted">Unique Geeks Technologies (Pty) Ltd</div>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <i class="icon-location3 mr-2"></i><span class="mr-2">Venda</span>
                <i class="icon-watch2 mr-2"></i><span class="mr-2">Full Time</span>
                <i class="icon-wallet mr-2"></i><span class="mr-2">Contract</span>
                <i class="icon-calendar mr-2"></i><span class="mr-2">2020-02-14</span>
                <div class="row">
                    <!--Remove this section to JobSeekers. Its for admin and Recruiter-->
                    <div class="col-sm mt-2">
                        <a asp-action="RecruiterAppliedJobsDetails" asp-controller="JobAdvert" asp-route-id="1" class="btn btn-success auto">View</a>
                    </div>

                    <div class="col-sm mt-2">
                        <a asp-action="Edit" asp-controller="JobAdvert" asp-route-id="1" class="btn btn-primary auto">Edit</a>
                    </div>

                    <div class="col-sm mt-2">
                        <a asp-action="JobSeekerJobDetails" asp-controller="JobAdvert" asp-route-id="1"class="btn btn-danger auto">Delete</a>
                    </div>
                </div>

            </div>
        </div>
        <!-- /basic card -->
    </div>

</div> <!--Job Advert Card Container-->

Hustlers/Views/Shared/_JobSeekerLayout.cshtml
@{
    Layout = "_MasterLayout";
}


    <!-- Page header -->
    <div class="page-header page-header-dark">

        <!-- Main navbar -->
        <div class="navbar navbar-expand-md navbar-dark border-transparent">

            <div class="collapse navbar-collapse" id="navbar-mobile">

                <ul class="navbar-nav ml-auto">

                    <li class="nav-item dropdown">
                        <a href="#" class="navbar-nav-link">
                            <i class="icon-bell2"></i>
                            <span class="d-md-none ml-2">Notifications</span>
                            <span class="badge badge-mark border-white ml-auto ml-md-0"></span>
                        </a>
                    </li>

                    <li class="nav-item dropdown dropdown-user">
                        <a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
                            <img src="../../../../global_assets/images/image.png" class="rounded-circle mr-2" height="34" alt="">
                            <span>@HttpContextAccessor.HttpContext.Session.GetString("Username");</span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right">
                            <a asp-action="Profile" asp-controller="JobSeeker"class="dropdown-item"><i class="icon-user-plus"></i> My profile</a>
                            <a href="#" class="dropdown-item"><i class="icon-cog5"></i> Change Password</a>
                            <div class="dropdown-divider"></div>
                            <a asp-action="SignOut" asp-controller="User" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /main navbar -->
        <!-- Secondary navbar -->
        <div class="navbar navbar-expand-md navbar-dark border-top-0">
            <div class="text-center d-md-none w-100">
                <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-navigation">
                    <i class="icon-unfold mr-2"></i>
                    Navigation
                </button>
            </div>

            <div class="navbar-collapse collapse" id="navbar-navigation">
                <ul class="navbar-nav navbar-nav-highlight">
                    <li class="nav-item">
                        <a href="../full/index.html" class="navbar-nav-link">
                            <i class="icon-home4 mr-2"></i>
                            Dashboard
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="../full/index.html" class="navbar-nav-link">
                            <i class="icon- mr-2"></i>
                            My Jobs
                        </a>
                    </li>

                </ul>

            </div>
        </div>
        <!-- /secondary navbar -->

    </div>
    <!-- /page header -->
    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content">

                @RenderBody();
            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

Hustlers/Views/Shared/_MasterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dasdboard</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="~/lib/global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/layout.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/components.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/colors.min.css" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
    <!-- Core JS files -->
    <script src="~/lib/global_assets/js/main/jquery.min.js"></script>
    <script src="~/lib/global_assets/js/main/bootstrap.bundle.min.js"></script>
    <script src="~/lib/global_assets/js/plugins/loaders/blockui.min.js"></script>
    <script src="~/lib/global_assets/js/plugins/ui/slinky.min.js"></script>
    <script src="~/lib/global_assets/js/plugins/ui/fab.min.js"></script>
    <!-- /core JS files -->
    <!-- Theme JS files -->
    <script src="~/js/app.js"></script>
    <!-- /theme JS files -->

</head>

<body>

    @RenderBody()


</body>
</html>

Hustlers/Views/Shared/_RecruiterSideNavMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Main navigation -->
<div class="card-body p-0">
    <ul class="nav nav-sidebar" data-nav-type="accordion">

        <!-- Main -->
        <li class="nav-item-header mt-0"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
        <li class="nav-item">
            <a href="../full/index.html" class="nav-link">
                <i class="icon-home4"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <li class="nav-item nav-item-submenu nav-item-expanded nav-item-open">
            <a href="#" class="nav-link"><i class="icon-unfold"></i> <span>Job Advert</span></a>

            <ul class="nav nav-group-sub" data-submenu-title="Job Advert">
                <li class="nav-item"><a asp-action="Index" asp-controller="JobAdvert" class="nav-link">Create</a></li>
                <li class="nav-item"><a asp-action="JobAdvertList" asp-controller="JobAdvert" class="nav-link">View</a></li>
                <li class="nav-item"><a asp-action="RecruiterViewAppliedJobs" asp-controller="JobAdvert" class="nav-link">Applied Jobs</a></li>
            </ul>
        </li>

        <li class="nav-item">
            <a href="../full/index.html" class="nav-link">
                <i class="icon-people"></i>
                <span>Search Job Seekers</span>
            </a>
        </li>

        <!-- /main -->

    </ul>
</div>
<!-- /main navigation -->