Hustlers/Controllers/RecruiterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hustlers.Domain.Entities;
using Hustlers.Domain.Interfaces.Services;
using Hustlers.Domain.Models.RecruiterViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Hustlers.Controllers
{
    public class RecruiterController : Controller
    {
        private readonly IRecruiterService _recruiterService;
        private readonly ICompanyService _companyService;
        private ILogger<RecruiterController> _logger;
        public RecruiterController(IRecruiterService recruiterService, ILogger<RecruiterController> logger,
            ICompanyService companyService)
        {
            _recruiterService = recruiterService;
            _companyService = companyService;
            _logger = logger;
        }
        // GET: RecruiterController
        public ActionResult Index()
        {
            //Get User using id saved on a session when they login

            return View("Dashboard");
        }        
        
        [HttpGet]
        public ActionResult AdminViewRecruiter(string CompanyId)
        {
            //Get User using id saved on a session when they login

            //Load Companies

            var companies = _companyService.GetAll();
            //companies.Insert(0,new Company {CompanyName = "All",Id = "0" });
            var recruiters = _recruiterService.GetAll(CompanyId);

            SearchFilterAndDataModel searchFilterAndDataModel = new SearchFilterAndDataModel 
            {
               ViewRecruiterViewModel = (List<ViewRecruiterViewModel>)recruiters,
               Companies = (List<Company>)companies

            };
            return View("AdminViewRecruiter",searchFilterAndDataModel);
        }

        // GET: RecruiterController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RecruiterController/Create
        public ActionResult Create()
        {
            CreateRecruiterViewModel createRecruiterViewModel = new CreateRecruiterViewModel
            {
                Companies = _companyService.GetAll()
            };

            return View("AdminCreate",createRecruiterViewModel);
        }

        // POST: RecruiterController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateRecruiterViewModel createRecruiterViewModel)
        {
            CreateRecruiterViewModel createRecruiterModel = new CreateRecruiterViewModel
            {
                Companies = _companyService.GetAll(),
            };

            if (ModelState.IsValid)
            {
                _recruiterService.Create(createRecruiterViewModel);
                return RedirectToAction("JobSeekerRegistered", "User");
            }

            return View("AdminCreate",createRecruiterModel);
        }

        // GET: RecruiterController/Edit/5
        public ActionResult Edit(string id)
        {

            return View("AdminEdit",PrepareRecruiterEdit(id));
        }

        private EditRecruiterViewModel PrepareRecruiterEdit(string id)
        {
            var recruiter = _recruiterService.Get(id);

            var editRecruiterViewModel = new EditRecruiterViewModel
            {
                FirstName = recruiter.FirstName,
                LastName = recruiter.LastName,
                Email = recruiter.Email,
                Companies = _companyService.GetAll(),
                CompanyId = recruiter.CompanyId,
                Phone = recruiter.Phone,
                Username = "Call User Service",
                RecruiterId = id
            };

            return editRecruiterViewModel;
        }
        // POST: RecruiterController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditRecruiterViewModel editRecruiterViewModel, string id)
        {
            if(ModelState.IsValid)
            {
                editRecruiterViewModel.RecruiterId = id;
                _recruiterService.Update(editRecruiterViewModel);

                return RedirectToAction("AdminViewRecruiter");
            }
            else
            {
                return View("AdminEdit",PrepareRecruiterEdit(id));
            }
        }

        // GET: RecruiterController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RecruiterController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Hustlers/Views/Recruiter/AdminCreate.cshtml
@model CreateRecruiterViewModel;
@{
    ViewData["Title"] = "Edit Recruiter";
    Layout = "~/Views/Shared/_AdminRecruiterLayout.cshtml";
}

<form method="POST" asp-action="Create" asp-controller="Recruiter">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="FirstName">First name</label>
            <input type="text" name="FirstName" class="form-control">
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="LastName">Last name</label>
            <input type="text" name="LastName" class="form-control" />
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="Username">Username</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrepend2"></span>
                </div>
                <input type="text" name="Username" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="Phone">Phone</label>
            <input type="Phone" name="Phone" class="form-control">
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="Email">Email</label>
            <input type="email" name="Email" class="form-control">
        </div>

        <div class="col-md-4 mb-3">

            <label for="CompanyId">Company</label>
            <select ap-for="CompanyId" asp-items="@(new SelectList(Model.Companies,"Id","CompanyName"))" name="CompanyId" class="custom-select form-control">
            </select>
        </div>
    </div>

    <div class="form-row">

        <div class="col-md-4 mb-3">

            <label asp-for="Password">Password</label>
            <input type="password" name="Password" class="form-control">

        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="ConfirmPassword">Confirm Password</label>
            <input type="password" name="ConfirmPassword" class="form-control">
        </div>

        <div class="col-md-4 mt-4">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>

    </div>

</form>

Hustlers/Views/Recruiter/AdminEdit.cshtml
@model EditRecruiterViewModel;
@{
    ViewData["Title"] = "Create Recruiter";
    Layout = "~/Views/Shared/_AdminRecruiterLayout.cshtml";

    IList<SelectListItem> recruiterCompany = new List<SelectListItem>();

    foreach (var item in Model.Companies)
    {

        recruiterCompany.Add(new SelectListItem(item.CompanyName, item.Id, item.Id.Equals(Model.CompanyId) ? true : false));
    }
}


<form method="POST" asp-action="Edit" asp-route-id ="@Model.RecruiterId" asp-controller="Recruiter">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="FirstName">First name</label>
            <input type="text" name="FirstName" class="form-control" value="@Model.FirstName">
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="LastName">Last name</label>
            <input type="text" name="LastName" class="form-control" value="@Model.LastName">
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="Username">Username</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrepend2"></span>
                </div>
                <input disabled type="text" name="Username" class="form-control" value="@Model.Username">
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="Phone">Phone</label>
            <input type="text" name="Phone" class="form-control" value="@Model.Phone">
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="Email">Email</label>
            <input type="email" name="Email" class="form-control" value="@Model.Email">
        </div>

        <div class="col-md-4 mb-3">

            <label asp-for="CompanyId">Company</label>
            <select name="CompanyId" asp-items="@recruiterCompany"  class="custom-select form-control">
            </select>
        </div>
    </div>

    <div class="form-row">

        <div class="col-md-4">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>

    </div>

</form>

Hustlers/Views/Recruiter/AdminViewRecruiter.cshtml
@model SearchFilterAndDataModel;
@{
    ViewData["Title"] = "AdminViewRecruiter";
    Layout = "~/Views/Shared/_AdminRecruiterLayout.cshtml";
}

<form asp-action="AdminViewRecruiter" asp-controller="Recruiter" method="get" class="mb-5">
    <div class="row">

        <div class="col-md-6">
            <select asp-items="@(new SelectList(Model.Companies,"Id","CompanyName"))" asp-for="ViewRecruiterViewModel.FirstOrDefault().CompanyId" name="CompanyId" class="form-control">
            </select>
        </div>

        <div class="col-md-3">
            <button type="submit" class="btn btn-primary form-control">Search</button>
        </div>

    </div>
</form>

<!-- Basic table -->
<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">Recruiters</h5>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Username</th>
                    <th>Company</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            @{ 
                foreach (var item in Model.ViewRecruiterViewModel)
                {

                    int count = 0;
                    count = count + 1;

                    <tr>
                        <td>@count</td>
                        <td>@item.FullName</td>
                        <td>@item.Username</td>
                        <td>@item.CompanyName</td>
                        <td>
                            <a asp-action="Edit" asp-controller="Recruiter" asp-route-id="@item.RecruiterId" class="btn btn-primary"> Edit </a>
                            <a asp-action="Edit" asp-controller="Recruiter" asp-route-id="@item.RecruiterId" class="btn btn-danger"> Delete </a>
                        </td>
                    </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<!-- /basic table -->

Hustlers/Views/Recruiter/Dashboard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_AdminRecruiterLayout";
}

<div class="row">

    <div class="col-md-3">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Recruiters</h5>
            </div>

            <div class="card-body">
                <h6 class="font-weight-semibold">150</h6>
            </div>
        </div>
        <!-- /basic card -->
    </div>

    <div class="col-md-3">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Companies</h5>
            </div>

            <div class="card-body">
                <h6 class="font-weight-semibold">85</h6>
            </div>
        </div>
        <!-- /basic card -->
    </div>

</div>
<!-- /Dashboard Satats -->